### ISSUE TITLE
modrinth: some modpacks fail with "only DEFLATED entries can have EXT"

### ISSUE THREAD

**Issue by itzg** [itzg/mc-image-helper#285]
[From Discord](https://discord.com/channels/660567679458869252/660569641550217327/1139840227339423785)

```yaml
version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 24454:24454/udp
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: MODRINTH
      MODRINTH_LOADER: FABRIC
      OPS: "Allexio"
      MEMORY: "5G"
      MODRINTH_PROJECT: "https://modrinth.com/modpack/allexio-vanilla++/version/0.3-server"
      VANILLATWEAKS_SHARECODE: IdYdcI
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data     
```

Results in error
```
fabric-120-mc-1  | me.itzg.helpers.errors.GenericException: Failed to read modpack index: only DEFLATED entries can have EXT descriptor
```

See https://discord.com/channels/660567679458869252/1139910332526121021/1139921427831738369
