### ISSUE TITLE
Support default values in environment variable interpolation

### ISSUE THREAD

**Issue by AngrySoundTech** [itzg/mc-image-helper#29]
It would be nice if were were able to set default values in config variables, to be able to be overrided.

For this, I'd propose something similar to [Shell Parameter Exansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html), so for example

```yml
database:
  host: ${CFG_DATABASE_HOST:-mariadb}
  database: ${CFG_DATABASE_DATABASE:-minecraft}
  password: ${CFG_DATABASE_PASSWORD}
```
with env vars set of
```env
CFG_DATABASE_HOST=mysql
CFG_DATABASE_PASSWORD=letmein
```
would result in
```yml
database:
  host: mysql
  database: minecraft
  password: letmein
```
