### ISSUE TITLE
Add TOML support for patch-set operation

### ISSUE THREAD

**Issue by itzg** [itzg/mc-image-helper#339]
[Discussed in Discord](https://discord.com/channels/660567679458869252/660567682751528981/1172672344842571847)

**Comment by itzg** [comment]
@alexstaeding heads up, TOML support is about to be added but [the library I'm using](https://github.com/FasterXML/jackson-dataformats-text/tree/master/toml) writes out the processed TOML as valid, but not pretty TOML:

```toml
abc.foo = 1
abc.bar = 2
abc.xyz = [{foo = 1, bar = 2}]
```
