### ISSUE TITLE
Curseforge should also have a --force-synchronize env-var option similar to installers for Vanilla and Marinth

### ISSUE THREAD

**Issue by jpsenior** [itzg/mc-image-helper#409]
I am working on using an AUTO_CURSEFORGE minecraft server configuration aginst a fairly old modpack, and am trying to distribute newer versions of mods to both clients and the server out of band.  If we expose 'force synchronization' to the user, I might be able to get around this.

There are command line options available in mc-image-helper for [Marilith](https://github.com/itzg/mc-image-helper/blob/7284455921ef118cc61c58965dde55c14f751a54/src/main/java/me/itzg/helpers/modrinth/InstallModrinthModpackCommand.java#L66
) as environment variable `MODRINTH_FORCE_SYNCHRONIZE` and [Vanilla Minecraft](https://github.com/itzg/mc-image-helper/blob/7284455921ef118cc61c58965dde55c14f751a54/src/main/java/me/itzg/helpers/vanillatweaks/VanillaTweaksCommand.java#L80) with env var `VC_FORCE_SYNCHRONIZE`.

It would be really ideal to also have a `CF_FORCE_CYNCHRONIZE` variable available for usage here in  [InstallCurseForgeCommand.java](https://github.com/itzg/mc-image-helper/blob/7284455921ef118cc61c58965dde55c14f751a54/src/main/java/me/itzg/helpers/curseforge/InstallCurseForgeCommand.java#L127) alongside with the sync support of other installers.

In [Documentation](https://github.com/itzg/docker-minecraft-server/blob/master/docs/types-and-platforms/mod-platforms/auto-curseforge.md) we see other mc-image-helper environment variables that are documented through exposure of mc-image-helper features under the hood.  Unfortunately, without locally forking docker-minecraft-server, I'm unable to provide a mechanism to append a command line argument towards the curse installation process.

On the client-side, we can easily generate new client manifests file as a 'Curseforge Export' profile, and it works handily between other minecraft installations.

However, on the server, we cannot repackage this exported manifest file and spin a workable server off of it for this particular modpack.

The obvious answer would be to locally modify the .jar files and just disable automatic synchronization after the first boot installation has completed and we can manipulate the minecraft mods directly on disk, then simply restart.

I have tried a few workarounds here, delete original mod, add new mod, and restart.

On penultimate restart, the mod referenced in the manifest file was simply re-downloaded again, resulting in a mod conflict with the new file we dropped in place:

I'm trying to update CyclopsCore here from 1.6.4 -> 1.6.7 as an example.

So step 1, we remove the original 1.6.4 and simply replace with 1.6.7 to see what happens - be mindful that 1.6.4 was removed:

```
  /opt/minecraft/mods$  cp ~/CyclopsCore-1.12.2-1.6.7.jar
  /opt/minecraft/mods$  rm CyclopsCore-1.12.2-1.6.4.jar
  /opt/minecraft$ docker-compose up
  ...
  ```

Observing the docker-minecraft-server logs, we see a reinstall of this mod due to its presence in manifest.json ([Code](https://github.com/itzg/mc-image-helper/blob/7284455921ef118cc61c58965dde55c14f751a54/src/main/java/me/itzg/helpers/curseforge/CurseForgeInstaller.java#L273)):

```
mc_1  | [mc-image-helper] 07:27:00.489 WARN  : Re-installing due to missing files from modpack: [mods/CyclopsCore-1.12.2-1.6.4.jar]
mc_1  | [mc-image-helper] 07:27:01.441 INFO  : Processing modpack 'SkyFactory 4 - 4.2.4' (skyfactory-4) @ 296062:3565683
```

We observe the mod marked as synched has now been downloaded, and later loaded.

```
mc_1  | [mc-image-helper] 07:27:03.699 INFO  : Mod file ./mods/Inspirations-1.12.2-0.2.9.jar already exists
mc_1  | [mc-image-helper] 07:27:03.714 INFO  : Mod file ./mods/PlaneFix-1.12.2-1.0.0.jar already exists
  ---> mc_1  | [mc-image-helper] 07:27:03.714 INFO  : Downloaded mod file mods/CyclopsCore-1.12.2-1.6.4.jar
mc_1  | [mc-image-helper] 07:27:03.715 INFO  : Mod file ./mods/journeymap-1.12.2-5.7.1.jar already exists
mc_1  | [mc-image-helper] 07:27:03.716 INFO  : Mod file ./mods/Uppers-0.0.6.jar already exists
```

This eventually results in a mod conflict, as the 1.6.7 .jar file dropped in the mods folder is still present, and the new 1.6.4 appears alongside this.
```mc_1  | [07:27:27] [Server thread/FATAL] [FML]: Found a duplicate mod cyclopscore at [./mods/CyclopsCore-1.12.2-1.6.4.jar, ./mods/CyclopsCore-1.12.2-1.6.7.jar]
mc_1  | [07:27:27] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
mc_1  | net.minecraftforge.fml.common.DuplicateModsFoundException:
mc_1  | Duplicate Mods:
mc_1  |         cyclopscore : /data/./mods/CyclopsCore-1.12.2-1.6.4.jar
mc_1  |         cyclopscore : /data/./mods/CyclopsCore-1.12.2-1.6.7.jar
mc_1  |
```

As a result of this behavior, a server administrator cannot interrupt this sequence to overwrite mods.

I suspect the only workaround I have is manually modifying the manifest json, but I guess that also exposes some other issues, particularly around the difficulty to manually get all of the individual mod file IDs manually from curseforge one by one, or if such a thing would work.

**Comment by jpsenior** [comment]
Actually, it seems an easier option as well is to use `CF_IGNORE_MISSING_FILES`. This mechanism also worked to prevent the re-download of 1.6.4.

**Comment by itzg** [comment]
I feel like you haven't read the documentation closely

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/

Everything you described is already addressed there such as loading unpublished manifest json. Please don't get distracted by looking at the mc-image-helper source code. That is only one piece in the overall solution.

**Comment by jpsenior** [comment]
Thanks for your reply.
I suppose the unique constraint here is that the actual mainfest.json is actually untouched. The CurseForge user interface client, while it does allow 'Add Additional Content' to incrementally add individual mods on top of the original modpack, the original modpack manifest json is always unchanged. This makes it quite difficult to sync client mods to server mods here, so I have to go out-of-band to replace specific versions.

The way I see this is the docker container itself is just an interface to mc-image-helper, so the logic needs to be handled here.

I have tried some syntax for instance include/exclude files, but it seems this functionality isn't version aware for strings, and I'm not really wanting to look up individual file IDs.

I'm just looking for a method to do a few things:
1) Ensure that I can add new mods easily; (COPY_MODS_SRC=/path is okay for this)
2) Ensure that I can remove stale mods; (While CF_INCLUDE_EXCLUDE_FILE or CF_IGNORE_MISSING_FILES are sort of both related, neither of seem them do the cleanup themselves; removing that 1.6.4 version)
3) CF_INCLUDE_EXCLUDE_FILE doesn't seem to have the capability o specifying a mod name in addition to its desired version.  It seems in this case, I can just specify the broad-strokes mod name, or the file ID, but not a more human readable format.
4) I don't see CF_SYNCHRONIZE working with any mechanism on either CF_INCLUDE_EXCLUDE_FILE or CF_IGNORE_MISSING_FILES.


Moreover, the same page you have sent here referncing to CF_SYNCHRONIZE, (https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods) -- it seems this option doesn't actually work the way I was hoping and I was wondering why, so that's what led me to the code.

To me it looked like a bug... 

I don't believe that looking at mc-image-helper is a distraction, this is what helps us really understand what these args/flags are doing under the hood.

**Comment by jpsenior** [comment]
I stand corrected here, exclude includes file does indeed remove a mod if I specify a matching slug correctly with CF_SYNCHRONIZE=True

`mc_1  | [mc-image-helper] 17:15:32.025 INFO  : Removing old file mods/CyclopsCore-1.12.2-1.6.4.jar`

**Comment by itzg** [comment]
> Thanks for your reply. I suppose the unique constraint here is that the actual mainfest.json is actually untouched. The CurseForge user interface client, while it does allow 'Add Additional Content' to incrementally add individual mods on top of the original modpack, the original modpack manifest json is always unchanged. This makes it quite difficult to sync client mods to server mods here, so I have to go out-of-band to replace specific versions.

Use this to add additional files from CurseForge:

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/

> 
> The way I see this is the docker container itself is just an interface to mc-image-helper, so the logic needs to be handled here.

That's fair.

> 
> I have tried some syntax for instance include/exclude files, but it seems this functionality isn't version aware for strings, and I'm not really wanting to look up individual file IDs.
> 
> I'm just looking for a method to do a few things:
> 
> 1. Ensure that I can add new mods easily; (COPY_MODS_SRC=/path is okay for this)

Use https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files/

> 2. Ensure that I can remove stale mods; (While CF_INCLUDE_EXCLUDE_FILE or CF_IGNORE_MISSING_FILES are sort of both related, neither of seem them do the cleanup themselves; removing that 1.6.4 version)

They're not designed for that scenario. They're designed for mods that self-patch, rename themselves and therefore inadvertently trigger a re-install on next startup.

> 3. CF_INCLUDE_EXCLUDE_FILE doesn't seem to have the capability o specifying a mod name in addition to its desired version.  It seems in this case, I can just specify the broad-strokes mod name, or the file ID, but not a more human readable format.

It's not designed for that scenario. It's designed for excluding client-only mods that did not declare as such when published. The "broad-stroke mod name" seems pretty human readable to me and remains unambiguous and concise for the software to process.

> 4. I don't see CF_SYNCHRONIZE working with any mechanism on either CF_INCLUDE_EXCLUDE_FILE or CF_IGNORE_MISSING_FILES.

See above. You are misunderstanding what they are designed for. 

> 
> Moreover, the same page you have sent here referncing to CF_SYNCHRONIZE, (https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods) -- it seems this option doesn't actually work the way I was hoping and I was wondering why, so that's what led me to the code.
> 
> To me it looked like a bug...

It's working as designed. You need to concisely describe what you think is the bug. 

> 
> I don't believe that looking at mc-image-helper is a distraction, this is what helps us really understand what these args/flags are doing under the hood.

Fair enough, but just make sure you have read all of the features before diving into the code and claiming there's a bug for behavior that has been working as designed for quite a while.

My apologies if my variable naming convention has mislead you into expecting different behavior than designed. Naming variables is hard and compounded by the shear number of scenarios that modpacks induce and users like yourself demand.

**Comment by jpsenior** [comment]
Okay, this setup here seems to work perfectly! I'm logging the full configuration here as a comment in case someone googles and stumbles across the same situation.

```
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java8}
    restart: unless-stopped
    volumes:
    - ./data:/data
    environment:
      EULA: "true"
      MOTD: Welcome, family! Enjoy the orchard.
      ServerName: SkyFamily
      # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/
      TYPE: AUTO_CURSEFORGE
      # https://console.curseforge.com/
      CF_API_KEY: REDACTED
      CF_SLUG: "skyfactory-4"
      MEMORY: 6G
      VERSION: 1.12.2
      # https://github.com/DarkPacks/SkyFactory-4/wiki/Multiplayer-Instructions
      GENERATOR_SETTINGS: '{"Topography-Preset": "Sky Factory 4"}'
      LEVEL_TYPE: DEFAULT
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#curseforge
      # Ensure initial worldgen comes from the original modpack so the player correctly
      # spawns on a tree in the middle of nowhere.
      CF_SET_LEVEL_FROM: OVERRIDES

      # Disregard the cyclops-core version from the original manifest of skyfactory4.
      # If this mod is installed via the manifest, the installation is skipped.
      # skyfactory-4 ships with cyclops-core 1.6.4 by default.
      CF_EXCLUDE_MODS:
        cyclops-core
      # Specify a manually updated version targeting the specific version of cyclops-core
      CURSEFORGE_FILES: |
        cyclops-core@1.6.7

      # If any lingering matches from CF_EXCLUDE_MODS were present, this ensures
      # that those mods are removed from the fileystem cleanly.
      CF_FORCE_SYNCHRONIZE: "true"

    ports:
      - "16683:25565"
    user: "1001:1001"

volumes:
  data: {}
```
