### ISSUE TITLE
Modrinth command fails with some mods

### ISSUE THREAD

**Issue by trbntwo** [itzg/mc-image-helper#64]
Hello,
I am trying to make the docker-minecraft-server with an autodownload of modrinth mods. The problem is that some mods are downloaded and others are not, during the initial startup. The container keeps trying to download the mod but fails every time. The exact error message looks like this, for `docker compose up` without `-d`: 

```
[torben@t-desktop mctest04]$ docker compose up
[+] Running 1/1
 ⠿ Container mctest04  Recreated                                                                                                                                                                                                                                  0.3s
Attaching to mctest04
mctest04  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 1 1000 1000 82 Nov 23 09:50 /data'
mctest04  | [init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
mctest04  | [init] Resolving type given FABRIC
mctest04  | [init] Checking Fabric Launcher version information.
mctest04  | [init] Checking Fabric Loader version information.
mctest04  | [init] Downloading https://meta.fabricmc.net/v2/versions/loader/1.19.2/0.14.10/0.11.1/server/jar ...
mctest04  | [mc-image-helper] 09:50:16.272 INFO  : Downloading fabric-api-0.67.1+1.19.2.jar
mctest04  | [mc-image-helper] 09:50:17.101 ERROR : 'modrinth' command failed: Getting project  lithium
mctest04 exited with code 1
mctest04  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 1 1000 1000 222 Nov 23 09:50 /data'
mctest04  | [init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
mctest04  | [init] Resolving type given FABRIC
mctest04  | [init] Checking Fabric Launcher version information.
mctest04  | [init] Checking Fabric Loader version information.
mctest04  | [mc-image-helper] 09:50:19.031 INFO  : Downloading fabric-api-0.67.1+1.19.2.jar
mctest04  | [mc-image-helper] 09:50:19.235 ERROR : 'modrinth' command failed: Getting project  lithium
mctest04 exited with code 1
```


All mods are available in the appropriate version and there is no difference between using the slugs or IDs.


I use docker-compose as management layer, and my `docker-compose.yaml` looks like this:


```
version: "3"
services:
  Minecraft:
    image: itzg/minecraft-server
    container_name: mctest04
    hostname: mctest04
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - /home/torben/Projekte/Docker/mctest04/:/data
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FABRIC"
      ENABLE_RCON: "true"
      RCON_PORT: "25566"
      RCON_PASSWORD: "1"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      USE_AIKAR_FLAGS: "true"
      GUI: "false"
      SNOOPER_ENABLED: "false"
      SERVER_NAME: "mctest04"
      SERVER_ICON: "https://avatars.githubusercontent.com/u/85442752?v=4"		# muss Webadresse sein
      MOTD: "testing"
      MAX_PLAYERS: "25"
      DIFFICULTY: "hard"
      NETWORK_COMPRESSION_THRESHOLD: "256"
      SIMULATION_DISTANCE: "8"
      VIEW_DISTANCE: "16"
      MODRINTH_PROJECTS: "fabric-api, lithium, lazydfu, ferrite-core, starlight, krypton, memoryleakfix, smoothboot-fabric, fastload, alternate-current, advancements-debug, dimthread, passivepregen, get-it-together-drops, brainier-bees, log-cleaner, notenoughcrashes, invview, damage-incorporated, bluemap, deathlog, no-chat-reports, debugify"
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: "true"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      TZ: "Europe/Berlin"
```


How to reproduce
Just copy the `docker-compose.yaml` and run it
